/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fixgamemanagement;

import java.awt.Frame;
import javax.swing.JDialog;
import fixgamemanagement.utils.filePicker;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author superspeed
 */
public class editGame extends javax.swing.JDialog
{

    /**
     * Creates new form editGame
     */
    Frame parentWindow;
    int height = 96, width = 293;
    Game current;
    public editGame(java.awt.Frame parent, boolean modal, Game in)
    {
        super(parent, modal);
        initComponents();
        this.current = in;
        this.parentWindow = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setImage = new javax.swing.JButton();
        labelTest = new javax.swing.JLabel();
        urlImage = new javax.swing.JButton();
        linkField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        setImage.setText("Import Image");
        setImage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                setImageActionPerformed(evt);
            }
        });

        labelTest.setText("jLabel1");

        urlImage.setText("Get Image from URL");
        urlImage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                urlImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelTest, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(linkField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urlImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setImage)
                .addGap(18, 18, 18)
                .addComponent(urlImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelTest, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setImageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_setImageActionPerformed
    {//GEN-HEADEREND:event_setImageActionPerformed
        JDialog getFile = new filePicker(parentWindow, true);
        getFile.setVisible(true);
        File gameImage = filePicker.selected;
        if (!(gameImage == null))
        {
            ImageIcon img = new ImageIcon(gameImage.getAbsolutePath());            
            Image image = img.getImage(); // transform it 
            Image newimg = image.getScaledInstance(width, height,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            img = new ImageIcon(newimg);
            current.setIcon(img);
        }
    }//GEN-LAST:event_setImageActionPerformed

    private void urlImageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_urlImageActionPerformed
    {//GEN-HEADEREND:event_urlImageActionPerformed
        
        try
        {
            URL imageLocation = new URL(linkField.getText());
            Image image = ImageIO.read(imageLocation);
            Image newimg = image.getScaledInstance(width, height,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            ImageIcon img = new ImageIcon(newimg);
            current.setIcon(img);
        }
        catch (Exception e) {e.printStackTrace();}
        
    }//GEN-LAST:event_urlImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTest;
    private javax.swing.JTextField linkField;
    private javax.swing.JButton setImage;
    private javax.swing.JButton urlImage;
    // End of variables declaration//GEN-END:variables
}
