/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fixgamemanagement;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.TreeModel;
import javax.swing.JTree.DynamicUtilTreeNode;
import javax.swing.tree.TreeNode;
import org.apache.commons.net.ftp.FTPFile;

/**
 *
 * @author superspeed
 */
public class loginWindow extends javax.swing.JDialog
{

    /**
     * Creates new form ftpWindow
     */
    static String[] cred;
    public loginWindow(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        cred = new String[2];
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        userNameField = new javax.swing.JTextField();
        passWordField = new javax.swing.JPasswordField();
        userNameTag = new javax.swing.JLabel();
        passwordTag = new javax.swing.JLabel();
        adminLoginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guestLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Please Login");
        setAlwaysOnTop(true);
        addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                formKeyPressed(evt);
            }
        });

        passWordField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                passWordFieldKeyPressed(evt);
            }
        });

        userNameTag.setText("Username");

        passwordTag.setText("Password");

        adminLoginBtn.setText("Login");
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                adminLoginBtnActionPerformed(evt);
            }
        });
        adminLoginBtn.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                adminLoginBtnKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        jLabel2.setText("or");

        guestLogin.setText("Continue as Guest");
        guestLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guestLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(adminLoginBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameTag)
                    .addComponent(passwordTag))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(guestLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameTag)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordTag)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addComponent(adminLoginBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(guestLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_adminLoginBtnActionPerformed
    {//GEN-HEADEREND:event_adminLoginBtnActionPerformed
        if (userNameField.getText().compareTo("") == 0 || passWordField.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(null, "Username or Password field is empty...");
            return;
        }
        cred[0] = userNameField.getText();
        cred[1] = String.valueOf(passWordField.getPassword());
        dispose();
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    private void guestLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guestLoginActionPerformed
    {//GEN-HEADEREND:event_guestLoginActionPerformed
        cred[0] = "Guest";
        cred[1] = "fix9909";
        dispose();
    }//GEN-LAST:event_guestLoginActionPerformed

    private void adminLoginBtnKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_adminLoginBtnKeyPressed
    {//GEN-HEADEREND:event_adminLoginBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLoginBtnKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
    {//GEN-HEADEREND:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void passWordFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_passWordFieldKeyPressed
    {//GEN-HEADEREND:event_passWordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            adminLoginBtnActionPerformed(new java.awt.event.ActionEvent(this, 0, "run"));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_passWordFieldKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JButton guestLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passWordField;
    private javax.swing.JLabel passwordTag;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameTag;
    // End of variables declaration//GEN-END:variables
}
