package fixgamemanagement;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author superspeed
 */
public class newGame extends javax.swing.JDialog
{

    /**
     * Creates new form newGame
     */
    static Game newG;
    public newGame(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        freePaidSelect.add(freeBtn);
        freePaidSelect.add(paidBtn);
        multiSingleSelect.add(multiBtn);
        multiSingleSelect.add(singleBtn);
    }
    
    public Game getGame(){return newG;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        multiSingleSelect = new javax.swing.ButtonGroup();
        freePaidSelect = new javax.swing.ButtonGroup();
        rhyBtn = new javax.swing.JCheckBox();
        simBtn = new javax.swing.JCheckBox();
        raceBtn = new javax.swing.JCheckBox();
        sportsBtn = new javax.swing.JCheckBox();
        escapeBtn = new javax.swing.JCheckBox();
        actionBtn = new javax.swing.JCheckBox();
        advenBtn = new javax.swing.JCheckBox();
        stratBtn = new javax.swing.JCheckBox();
        puzBtn = new javax.swing.JCheckBox();
        shootBtn = new javax.swing.JCheckBox();
        fightBtn = new javax.swing.JCheckBox();
        cardBtn = new javax.swing.JCheckBox();
        artBtn = new javax.swing.JCheckBox();
        coopBtn = new javax.swing.JCheckBox();
        designBtn = new javax.swing.JCheckBox();
        violentBtn = new javax.swing.JCheckBox();
        goreBtn = new javax.swing.JCheckBox();
        horrorBtn = new javax.swing.JCheckBox();
        aComBtn = new javax.swing.JCheckBox();
        fpsBtn = new javax.swing.JCheckBox();
        kidBtn = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        v1 = new javax.swing.JCheckBox();
        v2 = new javax.swing.JCheckBox();
        v3 = new javax.swing.JCheckBox();
        v4 = new javax.swing.JCheckBox();
        v5 = new javax.swing.JCheckBox();
        r1 = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        title = new javax.swing.JLabel();
        r3 = new javax.swing.JCheckBox();
        singleBtn = new javax.swing.JRadioButton();
        s1 = new javax.swing.JCheckBox();
        multiBtn = new javax.swing.JRadioButton();
        s2 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        stationTag = new javax.swing.JLabel();
        rc = new javax.swing.JCheckBox();
        nameField = new javax.swing.JTextField();
        nameTag = new javax.swing.JLabel();
        addGameBtn = new javax.swing.JButton();
        playerValue = new javax.swing.JTextField();
        freeBtn = new javax.swing.JRadioButton();
        paidBtn = new javax.swing.JRadioButton();
        genreTag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rhyBtn.setText("Rhythm");

        simBtn.setText("Simulation");

        raceBtn.setText("Racing");

        sportsBtn.setText("Sports");

        escapeBtn.setText("Escape");

        actionBtn.setText("Action");

        advenBtn.setText("Adventure");

        stratBtn.setText("Strategy");

        puzBtn.setText("Puzzle");

        shootBtn.setText("Shooter");

        fightBtn.setText("Fighting");
        fightBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fightBtnActionPerformed(evt);
            }
        });

        cardBtn.setText("Card");

        artBtn.setText("Art");

        coopBtn.setText("Co-op");

        designBtn.setText("Design");

        violentBtn.setText("Violent");

        goreBtn.setText("Gore");

        horrorBtn.setText("Horror");

        aComBtn.setText("Adult Comedy");

        fpsBtn.setText("FPS");

        kidBtn.setText("Kid");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        v1.setText("Vive 1");

        v2.setText("Vive 2");

        v3.setText("Vive 3");

        v4.setText("Vive 4");

        v5.setText("Vive 5");

        r1.setText("Rift 1");

        r2.setText("Rift 2");

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setText("Add a Game");

        r3.setText("Rift 3");

        singleBtn.setText("Singleplayer");

        s1.setText("Sitting 1");

        multiBtn.setText("Multiplayer (How many)");

        s2.setText("Sitting 2");

        s3.setText("Sitting 3");

        s4.setText("Sitting 4");

        stationTag.setText("Check Each Station With the Game:");

        rc.setText("Race Chair");

        nameTag.setText("Game Name:");

        addGameBtn.setText("Add Game");
        addGameBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addGameBtnActionPerformed(evt);
            }
        });

        freeBtn.setText("Free");

        paidBtn.setText("Paid");

        genreTag.setText("Select Genre(s):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(stationTag))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rc)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(r3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(r2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(s1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(v4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(s2))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(r1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s4))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(v5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(s3))))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(multiBtn)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(singleBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameTag)
                                .addGap(18, 18, 18)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(freeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paidBtn))
                            .addComponent(genreTag)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fpsBtn)
                                    .addComponent(horrorBtn)
                                    .addComponent(aComBtn)
                                    .addComponent(kidBtn)
                                    .addComponent(rhyBtn)
                                    .addComponent(advenBtn)
                                    .addComponent(puzBtn)
                                    .addComponent(fightBtn))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shootBtn)
                                    .addComponent(stratBtn)
                                    .addComponent(actionBtn)
                                    .addComponent(escapeBtn)
                                    .addComponent(sportsBtn)
                                    .addComponent(raceBtn)
                                    .addComponent(simBtn)
                                    .addComponent(cardBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(artBtn)
                                    .addComponent(designBtn))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coopBtn)
                                    .addComponent(violentBtn)))
                            .addComponent(goreBtn))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(addGameBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stationTag)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameTag)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v1)
                            .addComponent(r2)
                            .addComponent(freeBtn)
                            .addComponent(paidBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v2)
                            .addComponent(r3)
                            .addComponent(genreTag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v3)
                            .addComponent(s1)
                            .addComponent(fpsBtn)
                            .addComponent(simBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v4)
                            .addComponent(s2)
                            .addComponent(horrorBtn)
                            .addComponent(raceBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v5)
                            .addComponent(s3)
                            .addComponent(aComBtn)
                            .addComponent(sportsBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r1)
                            .addComponent(s4)
                            .addComponent(kidBtn)
                            .addComponent(escapeBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rc)
                            .addComponent(rhyBtn)
                            .addComponent(actionBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(advenBtn)
                                    .addComponent(stratBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(puzBtn)
                                    .addComponent(shootBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fightBtn)
                                    .addComponent(cardBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(artBtn)
                                    .addComponent(coopBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(designBtn)
                                    .addComponent(violentBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(goreBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(singleBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(multiBtn)
                                    .addComponent(playerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addComponent(addGameBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fightBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fightBtnActionPerformed
    {//GEN-HEADEREND:event_fightBtnActionPerformed
    }//GEN-LAST:event_fightBtnActionPerformed

    private void addGameBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addGameBtnActionPerformed
    {//GEN-HEADEREND:event_addGameBtnActionPerformed
        try
        {
            //First Check if all input fields have been used
            if (!(freeBtn.isSelected() || paidBtn.isSelected())) throw new Exception();
            if (nameField.getText().isEmpty()) throw new Exception();
            if (!(v1.isSelected() || v2.isSelected() || v3.isSelected() || v4.isSelected() || v5.isSelected() ||
                    r1.isSelected() || r2.isSelected() || r3.isSelected() || s1.isSelected() || s2.isSelected() || 
                    s3.isSelected() || s4.isSelected() || rc.isSelected())) throw new Exception();
            
            if (!(aComBtn.isSelected() || actionBtn.isSelected() || advenBtn.isSelected() || artBtn.isSelected() || cardBtn.isSelected() ||
                    coopBtn.isSelected() || designBtn.isSelected() || escapeBtn.isSelected() || fightBtn.isSelected() || fpsBtn.isSelected() ||
                    goreBtn.isSelected() || horrorBtn.isSelected() || kidBtn.isSelected() || puzBtn.isSelected() || raceBtn.isSelected() || 
                    rhyBtn.isSelected() || shootBtn.isSelected() || simBtn.isSelected() || sportsBtn.isSelected() || stratBtn.isSelected() || violentBtn.isSelected())) throw new Exception();
            if (!(singleBtn.isSelected() || multiBtn.isSelected())) throw new Exception();
            
            ArrayList<String> genre = new ArrayList<>(), stations = new ArrayList<>();
            newG = new Game();
            newG.setName(nameField.getText());            
            newG.setMulti(multiBtn.isSelected());
            //Get Stations
            if (v1.isSelected()) stations.add(v1.getText());
            if (v2.isSelected()) stations.add(v2.getText());
            if (v3.isSelected()) stations.add(v3.getText());
            if (v4.isSelected()) stations.add(v4.getText());
            if (v5.isSelected()) stations.add(v5.getText());
            if (r1.isSelected()) stations.add(r1.getText());
            if (r2.isSelected()) stations.add(r2.getText());
            if (r3.isSelected()) stations.add(r3.getText());
            if (s1.isSelected()) stations.add(s1.getText());
            if (s2.isSelected()) stations.add(s2.getText());
            if (s3.isSelected()) stations.add(s3.getText());
            if (s4.isSelected()) stations.add(s4.getText());
            if (rc.isSelected()) stations.add(rc.getText());
            newG.setStations(stations);
            //Get genres
            if (aComBtn.isSelected()) genre.add(aComBtn.getText());
            if (actionBtn.isSelected()) genre.add(actionBtn.getText());
            if (advenBtn.isSelected()) genre.add(advenBtn.getText());
            if (artBtn.isSelected()) genre.add(artBtn.getText());
            if (cardBtn.isSelected()) genre.add(cardBtn.getText());
            if (coopBtn.isSelected()) genre.add(coopBtn.getText());
            if (designBtn.isSelected()) genre.add(designBtn.getText());
            if (escapeBtn.isSelected()) genre.add(escapeBtn.getText());
            if (fightBtn.isSelected()) genre.add(fightBtn.getText());
            if (fpsBtn.isSelected()) genre.add(fpsBtn.getText());
            if (goreBtn.isSelected()) genre.add(goreBtn.getText());
            if (horrorBtn.isSelected()) genre.add(horrorBtn.getText());
            if (kidBtn.isSelected()) genre.add(kidBtn.getText());
            if (puzBtn.isSelected()) genre.add(puzBtn.getText());
            if (raceBtn.isSelected()) genre.add(raceBtn.getText());
            if (rhyBtn.isSelected()) genre.add(rhyBtn.getText());
            if (shootBtn.isSelected()) genre.add(shootBtn.getText());
            if (simBtn.isSelected()) genre.add(simBtn.getText());
            if (sportsBtn.isSelected()) genre.add(sportsBtn.getText());
            if (stratBtn.isSelected()) genre.add(stratBtn.getText());
            if (violentBtn.isSelected()) genre.add(violentBtn.getText());
            newG.setGenre(genre);
            newG.setPremium(freeBtn.isSelected());
            //Get multi/single player
            if (multiBtn.isSelected()) {newG.setMulti(true); newG.setPlayers(Integer.parseInt(playerValue.getText()));}
            else {newG.setMulti(false); newG.setPlayers(1);}
            newG.setCopies(stations.size());
            
            
            
            
            this.dispose();
        }//End try
        catch (Exception e)
        {
            e.printStackTrace();
            //Print error that the game was not able to be added
            JOptionPane.showMessageDialog(null, "Error Adding Game, please double check each field");
        }//End catch
    }//GEN-LAST:event_addGameBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aComBtn;
    private javax.swing.JCheckBox actionBtn;
    private javax.swing.JButton addGameBtn;
    private javax.swing.JCheckBox advenBtn;
    private javax.swing.JCheckBox artBtn;
    private javax.swing.JCheckBox cardBtn;
    private javax.swing.JCheckBox coopBtn;
    private javax.swing.JCheckBox designBtn;
    private javax.swing.JCheckBox escapeBtn;
    private javax.swing.JCheckBox fightBtn;
    private javax.swing.JCheckBox fpsBtn;
    private javax.swing.JRadioButton freeBtn;
    private javax.swing.ButtonGroup freePaidSelect;
    private javax.swing.JLabel genreTag;
    private javax.swing.JCheckBox goreBtn;
    private javax.swing.JCheckBox horrorBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox kidBtn;
    private javax.swing.JRadioButton multiBtn;
    private javax.swing.ButtonGroup multiSingleSelect;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameTag;
    private javax.swing.JRadioButton paidBtn;
    private javax.swing.JTextField playerValue;
    private javax.swing.JCheckBox puzBtn;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r2;
    private javax.swing.JCheckBox r3;
    private javax.swing.JCheckBox raceBtn;
    private javax.swing.JCheckBox rc;
    private javax.swing.JCheckBox rhyBtn;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox shootBtn;
    private javax.swing.JCheckBox simBtn;
    private javax.swing.JRadioButton singleBtn;
    private javax.swing.JCheckBox sportsBtn;
    private javax.swing.JLabel stationTag;
    private javax.swing.JCheckBox stratBtn;
    private javax.swing.JLabel title;
    private javax.swing.JCheckBox v1;
    private javax.swing.JCheckBox v2;
    private javax.swing.JCheckBox v3;
    private javax.swing.JCheckBox v4;
    private javax.swing.JCheckBox v5;
    private javax.swing.JCheckBox violentBtn;
    // End of variables declaration//GEN-END:variables
}
